[role="pagenumrestart"]
[[intro_what_is_the_lightning_network]]
== Introduction

_마스터링 라이트닝 네트워크_ 에 오신 것을 환영합니다!

((("Lightning Network (generally)", seealso="innovations in Lightning", id="ix_01_introduction-asciidoc0", range="startofrange")))라이트닝 네트워크(줄여서 LN)는, 사람들이 온라인에서 가치를 교환하는 방식을 바꾸고 있고, 비트코인 역사상 가장 흥미로운 발전 중 하나입니다. 
오늘날, 2021년에, 라이트닝 네트워크는 여전히 초기 단계입니다. 라이트닝 네트워크는 똑똑하고, 독창적인 방법으로 비트코인을 사용하는 프로토콜입니다. 비트코인 위의 레이어 2 기술이죠.

라이트닝 네트워크의 개념은 2015년에 제안되었고, 첫 구현은 2018년에 시작되었습니다. 2021년 현재, 우리는 더 나은 개인 정보 보호, 속도, 규모에서 라이트닝 네트워크가 비트코인에 제공하는 기회를 보기 시작했습니다. 
라이트닝 네트워크의 핵심 개념과 함께, 여러분은 스스로를 위한 기회를 창출하고, 네트워크의 미래를 만드는 데 기여할 수 있습니다.

우리는 여러분이 비트코인에 대한 기초 지식을 이미 갖고 있다고 가정합니다. 그러지 않다면 걱정하지 마세요. 우리는 <<bitcoin_fundamentals_review>>에서, 여러분이 라이트닝 네트워크를 이해하기 위해 반드시 알아야하는, 핵심 비트코인 용어들을 설명할 것입니다. 비트코인에 대해 더 자세히 배우고 싶다면, 안드레아스 M. 안토노폴로스의 _비트코인, 공개 블록체인 프로그래밍_ 2판(O'Reilly, 한글 번역본)을 읽으셔도 됩니다. 영문판은 https://github.com/bitcoinbook/bitcoinbook 에서 무료로 이용 가능합니다.

이 책의 대부분은 프로그래머들을 위해 작성되었지만, 초기 몇몇 챕터들은 프로그래머가 아니어도 누구나 이해하실 수 있도록 작성되었습니다. 이번 챕터에서, 우리는 몇 가지 용어로 시작하여, 신뢰 개념과 이러한 시스템의 적용에 대해 알아본 뒤, 마지막으로 라이트닝 네트워크의 역사와 미래를 얘기해보겠습니다. 그럼 시작하겠습니다.

=== 라이트닝 네트워크 기본 개념들

((("Lightning Network (generally)","basic concepts", id="ix_01_introduction-asciidoc1", range="startofrange")))라이트닝 네트워크가 어떻게 동작하는지 살펴볼 때, 헷갈릴 법한 몇 가지 기술 용어들을 만날 것입니다. 모든 개념과 용어들은 책과 용어집에 자세히 설명되어 있지만, 몇몇 기초 정의를 알면 다음 두 챕터의 내용을 더 쉽게 이해하실 수 있습니다. 아래에서 설명하는 모든 단어들을 이해하지 못해도, 괜찮습니다. 글을 읽을수록 더 많은 것을 이해하실 겁니다.

블록체인:: ((("blockchain","defined")))컴퓨터들의 네트워크가 만들어 낸 분산 거래 원장입니다. 예를 들어, 비트코인은 블록체인을 만드는 시스템입니다. 라이트닝 네트워크 자체는 블록체인도 아니고, 블록체인을 만드는 것도 아닙니다. 보안을 위해, 기존 외부 블록체인에 의존하는 네트워크입니다.

디지털 서명:: ((("digital signatures")))디지털 서명은, 디지털 메시지나 문서의 진위를 확인하기 위한 수학적 기법입니다. 유효한 디지털 서명은, 알려진 발신자가 메시지를 만들었고, 발신자가 메시지를 보냈다는 것을 부정할 수 없고, 메시지가 전송 중 변경되지 않았다고 믿을만한 근거를 수신자에게 제공합니다.

해쉬 함수:: ((("hash function, defined")))암호 해쉬 함수는, 데이터가 어떤 크기를 갖더라도, 고정된 크기의 문자열로 대응시켜주는 수학적 알고리즘입니다. 결과값을 통해 입력값을 계산하는 역연산은 불가능한, 단방향 함수입니다.

노드:: ((("node, defined")))네트워크에 참여하는 컴퓨터를 말합니다. 라이트닝 노드는 라이트닝 네트워크에 참여하는 컴퓨터입니다. 비트코인 노드는 비트코인 네트워크에 참여하는 컴퓨터입니다. 보통 라이트닝 네트워크 사용자는 라이트닝 노드와 비트코인 노드를 _동시에_ 실행시킬 것입니다.

온체인 vs 오프체인:: ((("on-chain payment","defined")))비트코인이나 다른 블록체인 상에서 트랜잭션으로 기록되면, _온체인_ 지불입니다. ((("off-chain payment")))블록체인 상에서는 보이지 않고, 라이트닝 노드들 간 지불 채널을 통한 전송은 _오프체인_ 지불입니다. 일반적으로 라이트닝 네트워크에서, 라이트닝 지불 채널을 열고 닫을 때가 유일한 온체인 트랜잭션입니다. 다른 온체인 트랜잭션 유형으로는, 스플라이싱(splicing)이라고 하는 채널 수정 트랜잭션이 있습니다. 스플라이싱은 채널 내에 맡긴 자금의 양을 수정할 때 사용됩니다.

지불:: ((("payment","defined")))비트코인의 ”트랜잭션”처럼, 라이트닝 네트워크에서 가치가 교환되는 것을 “지불”이라고 부릅니다.

지불 채널:: ((("payment channel", seealso="channel entries")))지불 채널은 라이트닝 네트워크에서 두 노드 간의 _재정적 관계_ 를 뜻합니다. 보통 두 라이트닝 노드들 간의 비트코인 제어권을 공유하는, 비트코인 다중서명 트랜잭션에 의해 구현됩니다.

전달 versus 전송:: ((("routing","sending versus")))((("sending, routing versus")))비트코인에서는 모든 사람에게 브로드캐스트하여 트랜잭션을 “전송”합니다. 그러나 라이트닝 네트워크는 송신자와 수신자 간 _경로_ 를 따르는 하나 이상의 지불 채널을 통해, 지불이 “전달”되는 전달 네트워크(routed network)를 이용합니다. 

트랜잭션:: ((("transaction, defined")))비트코인과 같은 자금의 소유권 이동을 기록하는 데이터 구조입니다. 라이트닝 네트워크는 자금의 소유권을 추적하기 위해 비트코인 트랜잭션(혹은 다른 블록체인의 트랜잭션)에 의존합니다.

더 상세하고 다양한 정의들은 <<gloassary>>에서 찾을 수 있습니다. 이 책 전반에서, 우리는 이 용어들이 무엇을 의미하는지, 어떻게 이 기술이 실제로 동작하는지 설명할 것입니다.

[TIP]
====
책에서 “비트코인”은 비트코인 시스템 자체를 의미하는 고유명사로 사용될 수도 있고, 화폐 단위를 의미할 수도 있습니다. 화폐 단위로서 각 비트코인은 1억 단위로 세분화되어 사토시로 불립니다(1 비트코인 = 1억 사토시). (((range="endofrange", startref="ix_01_introduction-asciidoc1")))
====

위 기초 용어들에 익숙해졌다면, 여러분들이 이미 알고 계시는 개념인, 신뢰(trust) 개념에 대해 설명하겠습니다.

=== 탈중앙화 네트워크에서 신뢰(Trust)

((("Lightning Network (generally)","trust in decentralized networks")))((("trustless systems","trust in decentralized networks")))여러분들은 종종 사람들이 비트코인과 라이트닝 네트워크를 “신뢰할 수 없다”고 말하는 것을 들었을 것입니다. 이것을 처음 접하면 혼란스러우실 수 있습니다. 결국, 신뢰는 좋은 것 아닐까요? 심지어 은행에선 이름에 신뢰를 붙이기도 하니까요. “신뢰할 수 없는” 시스템, 신뢰 없는 시스템은 나쁜 것 아닐까요? 

“신뢰할 수 없음(trustless)”의 의미는, 시스템에 참여하는 사람들끼리 서로 신뢰하지 않아도, 시스템이 동작한다는 것을 의미합니다. 비트코인 같은 탈중앙화 시스템에서, 여러분은 항상 여러분이 신뢰하는 사람들끼리만 거래할 수도 있습니다. 그러나 시스템은 여러분들이 신뢰하지 않는 사람과 거래해도, 사기당하지 않는다는 점을 보장해줍니다. 시스템에서 신뢰는 있으면 좋을 뿐이지, 반드시 있어야 하는 것은 아닙니다. 

여러분들이 돈을 맡기고 신뢰하는, 은행과 같은 전통적인 시스템과 비교해보세요. 만약 은행이 여러분들의 신뢰를 깨는 행위를 저질렀다면, 규제 기관이나 법원으로부터 돈 일부를 되찾을 수도 있습니다. 그러나 엄청난 시간, 돈과 노력이 들겠죠.

신뢰할 수 없음(trustless)은 신뢰가 없다는 것을 의미하지 않습니다. 시스템이 부정행위를 방지하기 때문에, 모든 거래에서 신뢰가 전제조건이 될 필요가 없다는 점, 여러분들이 신뢰하지 않는 사람들과도 거래가 가능하다는 점을 의미합니다. 

어떻게 라이트닝 네트워크가 동작하는지 알아보기 전에, _공평성 프로토콜(fair protocol)_ 이라고 부르는 비트코인과 라이트닝 네트워크의 기초 개념을 이해하는 것이 중요합니다. 공평성 프로토콜은, 신뢰하지 않는 서로가 중앙 기관 없이 공평한 결과를 낼 수 있는 방법을 말합니다. 비트코인 같은 탈중앙화 시스템의 핵심이라고 볼 수 있습니다.


=== 중앙 기관 없는 공평성

((("fairness, ensuring")))((("Lightning Network (generally)","fairness without central authority")))사람들이 이익을 위해 경쟁할 때, 협력과 거래를 위한 신뢰를 어떻게 쌓을 수 있을까요? 이 질문에 대한 답은, 경제학, 사회학, 행동심리학, 수학과 같은 과학적이고 인문학적 학문의 핵심입니다. 몇몇 학문들은 명성, 공평함, 도덕, 심지어 종교와 같은 "가벼운" 개념들이 답이라고 말합니다. 다른 학문은 참가자들이 자신의 이익을 목적으로 이성적으로 행동한다는 가정 하에, 구체적인 답을 주기도 합니다. 

넓은 의미에서, 이익을 위해 경쟁하는 개인들 간에서 공정한 결과를 보장하는 방법이 몇 가지 있습니다.

신뢰하는 사람들과 거래하기:: 이전 거래, 명성, 가족 관계 등을 바탕으로, 이미 신뢰하는 사람들끼리만 거래합니다. 가족처럼 소규모 단위에서 잘 동작하기 때문에, 협력 행동에서 가장 흔합니다. 그러나 규모가 커지지 않고, (그룹 내) 집단중심주의가 강한 사람의 편견으로부터 고통받습니다.

규칙 정하기:: 기관에서 상호작용을 위한 규칙을 정합니다. 규모적으로는 좀 더 낫지만, 기관이 영향을 미칠 수 있는 범위가 한정적이고, 관습과 전통의 차이로 인해 세계적으로 커질 순 없습니다. 기관이 커질수록 권력이 강해지고, 부패로 이어질 수 있다는 부작용도 있습니다. 

믿을 만한 제3자를 이용하기:: 공평함을 위해 모든 상호작용에 중개자를 두는 것입니다. 중개자의 감시를 위해 “규칙까지 정하면”, 규모를 더 확장시킬 수 있지만, 권력의 문제를 겪을 수도 있습니다. 중개자의 힘이 매우 강해지고, 부패로 이어질 수 있습니다. 권력의 집중은 시스템의 위험과 실패로 이어집니다.

게임 이론을 통한 공평성 프로토콜:: 마지막 카테고리는 인터넷과 암호학의 융합으로 비롯되었으며, 이 섹션의 주제입니다. 이것이 어떻게 동작하고, 장단점은 무엇인지 알아봅시다.

==== 중개자 없는 신뢰할 수 있는 프로토콜

((("fairness protocol","trusted protocols without intermediaries")))비트코인과 라이트닝 네트워크 같은 암호화 시스템에서, 여러분들은 신뢰하지 않는 사람들(혹은 컴퓨터)과 거래할 수 있습니다. 이것을 “신뢰할 수 없는(trustless)” 작업이라고 부릅니다. 실제로 신뢰하지 않는 건 아니겠지만요. 여러분들은 실행시키는 소프트웨어를 믿어야 하고, 소프트웨어가 구현하는 프로토콜이 공평한 결과를 만들 것이라고 믿어야 합니다. 

암호화 시스템과는 달리, 전통적인 금융 시스템은 공정한 결과를 보장하기 위해 은행과 같은 _신뢰받는 제3자_ 가 있어야 합니다. 이때 제3자에게 너무 많은 권력을 줄 수 밖에 없고, _장애 하나(단일 장애점, SPOF)_ 에도 취약하다는 점이 심각한 문제입니다. 만약 제3자가 신뢰를 위반하거나, 사기를 치려고 한다면, 신뢰는 깨지게 되겠죠.

여러분들이 암호화 시스템을 공부할 때마다, 다음과 같은 특정 패턴을 발견하실 겁니다. 시스템은 제3자에게 의존하는 것 대신에, 유인책과 억제책을 사용하여 불공정한 결과를 방지하려고 시도하는 것 말이죠. 암호화 시스템에서 여러분은 유인책과 억제책을 올바르게 적용할 규칙인 ((("protocol, defined")))_프로토콜_ 을 신뢰합니다. 프로토콜이 잘 설계되었다는 가정 아래입니다. 이 접근법의 장접은 두 가지 입니다. 여러분이 제 3자를 신뢰하지 않아도 괜찮고, 공정한 결과를 강요할 필요도 없습니다. 참가자들이 합의된 프로토콜을 따르고, 시스템 내에 머무른다면, 프로토콜의 인센티브 정책으로 강제성 없이 공평한 결과를 달성할 것입니다. 


((("game theory")))공평한 결과를 내기 위한 유인책과 억제책의 사용은 _게임 이론_ 이라고 불리는 수학의 한 분야입니다. 게임 이론에서는 “합리적인 결정을 내리는 사람들 간 전략적 상호 작용 모델”을 연구합니다."footnote:[위키피디아 https://en.wikipedia.org/wiki/Game_theory[entry on game theory]에 더 자세한 설명이 있습니다.] 비트코인과 라이트닝 네트워크처럼 참가자들 간 재정적 상호작용을 다루는 암호화 시스템에서는, 참가자들 간 사기를 방지하고, 신뢰하지 않는 사람들끼리도 공평한 결과를 내기 위해, 게임 이론에 많이 의존합니다.
 
게임 이론이 무엇이고, 암호화 시스템에서 게임 이론이 어떻게 사용되는지가 처음에는 혼란스럽고 낯선 개념일지도 모릅니다. 그러나 여러분들은 인지하지 못하셨겠지만, 일상생활에서 이미 게임 이론의 상황을 겪고 계실 수도 있습니다. 다음 섹션에서는 어린 시절을 예시로 들어, 게임 이론의 기초 원리를 이해해 볼 것입니다. 기초 원리를 이해하시면 여러분들은 게임 이론을, 블록체인을 다루는 어디에서나 보실 수 있고, 빠르고 직관적으로 이해하실 수 있으실 겁니다. 

((("fairness protocol", id="ix_01_introduction-asciidoc2", range="startofrange")))이 책에서 우리는 이 원리를 ((("fairness protocol","defined")))_공평성 프로토콜_ 이라고 부릅니다. 유인책과 억제책의 시스템을 사용하여, 서로 신뢰하지 않는 참가자들끼리 공평한 결과를 내도록 보장할 수 있는 프로세스를 의미합니다. 공평성 프로토콜은, 참가자들이 유인책과 억제책을 피할 수 없도록 보장하기 위해 필수입니다.

==== 구체적인 상황 속에서 공평성 프로토콜

((("fairness protocol","real-world example")))여러분들이 이미 친숙한 상황을 예로 들어 공평성 프로토콜을 살펴보도록 하죠.

부모님과 두 아이들이 가족 식사를 하고 있는 상황을 상상해봅시다. 아이들은 까다롭게 먹어요. 감자튀김만 먹으려고 합니다. 부모님들은 감자튀김 한 접시를 준비했습니다. (여러분들의 지역에 따라 감자튀김일 수도, 감자칩일 수도 있습니다.) 아이들은 감자튀김 한 접시를 나눠 먹어야 해요. 부모님은 각 아이들에게 감자튀김을 공정하게 나눠줘야 하는데, 항상 불평을 듣기 일쑤죠(거의 매일요). 공정하지 않는 상황이 매번 발생하면 싸울 수도 있습니다. 부모님들은 어떻게 해야 할까요?

아이들은 이익을 위해 다투면서, 서로 신뢰하지 않습니다. 이때 전략적으로 공평함을 달성할 수 있는 방법이 몇 가지 있습니다. 부모님들께서 흔하게 사용하시는 방법은, 감자튀김을 두 접시에 나눠 담는 방법입니다. 부모님이 신뢰 받는 제3자로서 권한을 사용하는 것이죠. 마치 거래하는 두 사람 간 사기를 방지하기 위해, 은행, 회계사, 변호사처럼 신뢰 받는 제3자가 대신하는 전통적인 금융과 유사합니다. 

이 시나리오의 문제점은 신뢰 받는 제3자에게 너무 많은 권력과 책임을 부여하는 것입니다. 이번 예시에서, 부모님은 전적으로 감자튀김을 동등하게 나눠야 하는 책임이 있습니다. 아이들은 단지 기다리고, 지켜보고, 불평할 뿐이죠. 아이들은 감자튀김을 공평하게 나누지 않고, 편애한다고 비난합니다. 감자튀김을 사이에 두고 상대방 것이 더 크다며, 소리치면서 부모님을 싸움에 끌어들입니다. 끔찍하지 않나요? 부모님들은 더 크게 소리질러야 할까요? 감자튀김을 다 치우면서? 다시는 감자튀김을 안주고, 아이들은 굶어야 한다고 말해야 할까요?

더 나은 해결책이 있습니다. 아이들에게 “나누고 선택하는” 게임을 가르쳐주는 것이죠. 매 점심 식사에서, 한 아이가 감자 튀김을 두 접시에 나누고, _나머지_ 아이가 무엇을 먹을지 선택하는 것입니다. 아이들은 바로 이 게임의 재미를 알아차립니다. 만약 한 아이가 실수하거나, 사기를 치려고 한다면, 다른 아이는 더 큰 접시를 선택해서 상대방을 “벌”할 수 있죠. 공평하게 나누는 것은, 두 아이들 모두에게 가장 큰 이익을 주지만, 특히 두 접시로 나누는 아이에게는 더 이익이 됩니다. 이 시나리오에서는 부정행위를 하는 사람만이 손해입니다. 부모님은 심지어 그들의 권한을 사용할 필요도 없고, 공평함을 강제할 필요도 없습니다. 모든 부모님들은 단지 _규칙을 강제하기만 하면_ 됩니다. 아이들이 “나누고”, “선택하는”, 역할을 피하지 않는 한, 프로토콜 자체로 어떤 간섭도 필요 없이, 공평한 결과를 보장할 수 있습니다. 부모님들은 편애할 수도 없고, 결과를 왜곡할 수도 없습니다.  

[경고]
====
1980년대 악명 높은 감자튀김 배틀을 잘 보여주고 있지만, 실제 저자들과 사촌들 간의 어린 시절 경험이 위 시나리오와 비슷한 것은 완전 우연입니다…그렇겠죠?
====

==== 블록을 구성할 때 보안 요소들

((("fairness protocol","security primitives as building blocks")))((("security primitives")))위와 같은 공평성 프로토콜이 작동하기 위해선, _보안 요소(security primitives)_ 라는 것이 필수적으로, 강제적으로 보장되어야 합니다. 첫번째 보안 요소는 _엄격한 시간 순서_ 입니다. “나누는” 행위는 반드시 “선택하는” 행위보다 먼저 일어나야 합니다. 바로 이해하기 어려우실 수 있겠습니다만, A 행위가 B 행위보다 먼저 일어나는 것을 보장할 수 없다면, 프로토콜은 붕괴되고 맙니다. 두번째 보안 요소는 _부인 방지를 약속하는 것_ 입니다. 각 아이들은 나눌지 선택할지, 각자의 역할을 확실히 선택해야 합니다. 또한 분할이 끝나면, 나누는 사람은 자신이 나눈 것을 확정해야 합니다. 선택한다거나, 다시 나누는 행위는 불가능하죠.

암호화 시스템은 공평성 프로토콜을 구성하는 다양한 방법들이 결합되어, 수많은 보안 요소들을 제공할 수 있습니다. 연속성과 확정성 외에도, 우리는 다른 여러 도구들을 이용할 수 있습니다.

- 데이터들의 지문으로서, 디지털 서명을 만드는 데 기초가 되는 해쉬 함수
- 인증, 부인방지, 비밀리에 소유권을 증명하는 데 사용되는 디지털 서명
- 권한이 있는 참가자들에게만 정보에 접근할 수 있도록 제한하는 암호화/복호화

이러한 도구들은 보안과 암호학에서 사용되는 요소들 중 일부에 불과합니다. 더 기초적인 요소들과 그것들의 결합들은 계속 만들어지고 있습니다.

일상생활에서 볼 법한 예시를 들어, 우리는 공평성 프로토콜의 하나인 “나누고 선택하는” 게임을 알아보았습니다. 이것은 단지, 보안 요소를 사용하여 블록을 구성하는 여러 방법들 중 하나입니다. 그러나 기초 원리는 항상 동일합니다. 둘 이상의 참가자들은 서로를 신뢰하지 않고, 서로 동의하는 프로토콜의 절차를 밟아가며 상호작용합니다. 프로토콜의 각 단계는, 참가자들이 이성적이라는 가정 하에, 사기를 치면 불이익을 받고, 공정하게 행동하면 정해진 결과를 받는 것을 보장하도록, 유인책과 억제책으로 구성되어 있습니다. 공평한 결과를 얻는 데 강요는 필요하지 않습니다. 단지 참가자들이 공통의 규칙을 깨지 않도록 하는 것만이 필요할 뿐이죠.

이제 여러분들은 기초 원리를 이해하셨으니, 이 원리를 비트코인, 라이트닝 네트워크, 또 다른 시스템들 어디에서나 보실 수 있을 겁니다. 특정한 예를 들어 살펴봅시다.

==== 공평성 프로토콜의 예시

((("fairness protocol","Proof of Work example")))((("PoW (Proof of Work) algorithm")))((("Proof of Work (PoW) algorithm")))가장 잘 알려진 공평성 프로토콜 예시는 비트코인의 합의(consensus) 알고리즘인 작업증명(Proof of Work, Pow)입니다. 비트코인에서 채굴자는 트랜잭션을 검증하고, 블록에 트랜잭션을 모으기 위해 경쟁합니다. 채굴자들을 신뢰하지 않고도, 그들이 사기를 치지 않는다는 것을 보장하기 위해서, 비트코인은 유인책과 억제책을 사용합니다. 모든 블록을 “증명”하는 “작업”을 하기 위해, 채굴자들은 하드웨어와 전기를 사용해야만 합니다. 채굴자들의 경쟁이 잘 이루어지는 이유는, 해시 함수의 결과값이 수많은 숫자들 중 랜덤으로 정해지는 특성때문입니다. 만약 채굴자들이 검증된 블록을 빨리 찾는다면, 그들은 해당 블록에 대해 보상을 받습니다. 네트워크에 블록을 올리기 위해 채굴자들은 많은 전기를 사용하죠. 이는 채굴자들이 블록 내 트랜잭션을 올바르게 검증할만한 동기가 충분하다는 것을 의미합니다. 만약 그들이 사기를 치거나 실수를 저질렀다면, 그들의 블록은 거절되고 그들이 “증명”하려고 사용한 전기는 낭비됩니다. 아무도 채굴자들에게 타당한 블록을 만들라고 강요하지 않았습니다. 보상과 손해가 그들이 그렇게 하도록 만들었을 뿐입니다. 프로토콜이 해야 할 일은 작업 증명으로 검증된 블록들만 받아들이는 것입니다.

라이트닝 네트워크의 다른 측면에서도 공평성 프로토콜의 원리를 발견할 수 있습니다.

* 채널에 지불하려는 사람들은 지불 트랜잭션을 네트워크에 올리기 전에, 서명된 환불 트랜잭션을 반드시 가지고 있습니다.

* 채널이 새 상태로 변경될 때마다, 이전 상태는 "철회"됩니다. 이로써 다른 사람이 네트워크에 이전 상태를 올리려고 한다면, 전체 잔액을 잃게 하고 처벌하도록 보장합니다.

* 지불하려는 사람들은 그들이 지불하면 환불되거나 이전 노드로부터 돈을 받을 수도 있다는 사실을 알고 있습니다.

계속해서 우리는 이 원리를 봅니다. 공정한 결과는 권위적으로, 강제적으로 나오지 않습니다. 공정한 것은 보상하고 부정 행위를 처벌하는, 프로토콜의 자연스러운 결과입니다. 공평성 프로토콜은 개인들이 자신의 이익을 추구하는 것을 이용하여, 공정한 결과로 이어지도록 합니다.

비트코인과 라이트닝 네트워크는 둘 다 공평성 프로토콜의 구현입니다. 그런데 라이트닝 네트워크는 왜 필요할까요? 비트코인만으로 충분하지 않나요?(((range="endofrange", startref="ix_01_introduction-asciidoc2")))

=== 라이트닝 네트워크가 필요한 이유

((("Lightning Network (generally)","motivation for", id="ix_01_introduction-asciidoc3", range="startofrange")))비트코인은 거래들을 기록하는, 세계적으로 복제된 공공 기록 장부 시스템입니다. 시스템에 참가하는 모든 컴퓨터들이 모든 거래를 보고, 검증하고, 저장합니다. 여러분들이 상상하시는 것처럼, 수많은 데이터들이 만들어지고 확장(트랜잭션을 빠르고, 많이 처리)하기 어렵습니다. 

비트코인이 성장하고 거래 수요가 많아질수록, 각 블록의 거래량은 블록 크기 한계에 도달할 때까지 증가할 것입니다.
블록이 "꽉 차면", 블록에 들어가지 못한 초과 거래들이 남아 대기하게 됩니다. 많은 사용자들은 거래를 기록할 블록의 공간을 사기 위해, 수수료를 계속 증가시킬 것입니다.

네트워크가 감당하기 힘들정도로 수요가 계속 많아진다면, 네트워크에 올라가지 못하고 기다리는 거래들이 더 많아질 것입니다. 수수로 경쟁으로 각 거래의 비용도 비싸져서, 수많은 작은 규모의 거래들(예를 들어, 소액 결제)은 수요가 많아지면 비경제적으로 됩니다.

이 문제를 해결하기 위해 더 많은 거래들을 위한 공간을 만들어서 블록 크기 한계를 증가시킬 수 있습니다. 블록 공간의 "공급" 증가는 거래 수수료에 대한 가격 균형을 낮출 것입니다.

그러나 블록 크기가 증가하게 되면, 노드를 운영하는 사람은 더 많은 비용을 내야 하고, 블록체인에 저장하고 검증할 때 더 많은 자원을 사용해야 합니다. 블록체인은 소문이 퍼지듯이 노드 간 전달로 정보를 확산시키는 프로토콜(gossip protocols)이기 때문에, 각 노드는 네트워크에서 발생한 모든 단일 거래들을 검증하고 알고 있어야 합니다. 게다가 검증 이후 노드의 이웃들에게 각 거래들과 블록을 전달해야 해서, 네트워크 대역폭 요구사항은 제곱으로 커집니다. 따라서, 블록 크기가 커지면, 각 노도들의 대역폭과 처리, 저장공간 요구사항도 커집니다. 이렇게 거래 용량이 증가하면 노드 수와 노드를 운영하는 사람 수가 줄어들어, 시스템이 중앙 집중화되는 부작용이 발생합니다. 노드를 운영하는 사람들이 노드를 실행해도 보상을 받지 못하기 때문에, 노드를 운영하는 비용이 비싸지면, 돈이 많은 소수의 운영자들만 노드를 운영하게 됩니다.

==== 블록체인 확장시키기

((("blockchain","scaling", id="ix_01_introduction-asciidoc4", range="startofrange")))((("Lightning Network (generally)","scaling blockchains", id="ix_01_introduction-asciidoc5", range="startofrange")))블록 크기를 증가시키거나 블록 시간을 감소시키면, 네트워크의 중앙화에 관한 부작용이 심각해집니다. 아래에서 몇 가지 계산을 통해 수치로 보여드리겠습니다.

비트코인 사용량이 늘어나서 네트워크가 초당 40,000 트랜잭션을 처리해야 한다고 가정해봅시다. 이는 Visa 네트워크의 이용량이 많을 때 거래 처리 속도와 비슷합니다.

평균적으로 트랜잭션 하나 당 250바이트라고 했을 때, 모든 트랜잭션을 받기 위해 초당 10메가바이트(MBps)나 초당 80메가비트(Mbps, 1바이트 = 8비트)의 데이터 스트림이 만들어집니다.
이때 다른 노드들에게 거래 정보를 전달하는 트래픽은 고려하지 않았습니다.
고속 광섬유나 5G 모바일 환경에서는 10 MBps를 충분히 감당할 수 있겠지만, 이런 환경을 만족시킬 수 없는 사용자는 노드를 실행시킬 수 없습니다. 특히 인터넷이 잘 터지지 않거나, 많은 사람들이 인터넷을 이용하기 힘든 나라에서는 더욱 힘들겠죠.

또, 사용자들은 대역폭에 관한 요구가 더 많아지겠지만, 단지 거래를 수신하기 위해 사용자들이 여기에 돈을 쓰는건 기대하기 힘듭니다.

게다가 정보를 저장하는 공간은 매일 864기가바이트가 필요합니다. 이건 거의 1테라바이트(TB) 혹은 하드 드라이브 하나 정도의 크기입니다.

초당 40,000개의 타원 곡선 디지털 서명 알고리즘(ECDSA)을 검증하는 것도 불가능합니다(다음 주소를 살펴보세요. https://bitcoin.stackexchange.com/questions/95339/how-many-bitcoin-transactions-can-be-verified-per-second[StackExchange의 관련 글]). 매우 비싼 하드웨어가 아닌 이상, 비트코인 블록체인의 _초기 블록 다운로드(Initial Block Download, IBD)_ 를 거의 불가능하게 만듭니다(비트코인에서 동기화하고 검증하는 모든 과정은 원시 블록(genesis block)에서 시작합니다.). 

초당 40,000 트랜잭션이 많아 보일수도 있지만, 사람들이 몰리는 시간대에 전통적인 금융 지불 네트워크의 상황과 비슷한 수준입니다. 디바이스끼리의 결제, 소액거래, 그리고 여러 애플리케이션에서 일어난 혁신들로 이것보다 더 많은 거래가 필요할 수도 있습니다.

간단히 말해서, 탈중앙화 방식을 갖고 전세계 모든 거래를 검증할 수 있는 블록체인으로 확장할 수는 없습니다.

_그런데 각 노드들이 모든 단일 거래를 검증하거나 알아야 할 필요가 없다면 어떻게 될까요? 비트코인 네트워크의 보안성을 잃지 않으면서, 확장 가능한(트랜잭션을 더 많이, 빠르게 처리할 수 있는) 오프체인 거래를 할 수 있다면 어떻게 될까요?_

2015년 2월, 조셉 푼(Joseph Poon)과 테드데우스 드라이자(Thaddeus Dryja)는 "비트코인 라이트닝 네트워크: 확장 가능한 오프체인 즉시 지불"이라는 백서를 통해, 비트코인 확장성 문제의 해결책을 제안했습니다."footnote:[Joseph Poon and Thaddeus Dryja. "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments." DRAFT Version 0.5.9.2. January 14, 2016. https://lightning.network/lightning-network-paper.pdf[].]

백서(초안)에서, 푼과 드라이자는 비트코인이 Visa처럼 초당 47,000 트랜잭션을 처리하려면, 8GB 블록들이 필요할 것이라고 추정했습니다.
이 경우에 대규모 기업이나 산업을 운영하는 곳이 아닌, 개인이 노드를 실행하는 것은 완전히 불가능하게 됩니다.
결국 소수의 사용자들만 장부 상태를 검증할 수 있는 네트워크가 될 것입니다.
비트코인에서 탈중앙화를 유지하기 위해, 제3자를 믿지 않고 스스로 장부를 검증하는 사용자들이 필요합니다.
노드를 운영하는 비용이 감당하기 힘들 정도로 커지면, 사용자들은 장부 상태를 확인하기 위해 제3자를 신뢰해야 할 수 밖에 없습니다. 궁극적으로 비트코인의 신뢰 모델을 깨뜨리게 되죠.


라이트닝 네트워크는 새로운 레이어 2 네트워크를 제안합니다. 여기선 사용자들이 각 지불을 비트코인 블록체인에 트랜잭션을 올릴 필요 없이, 서로 P2P로 지불할 수 있습니다.
사용자들은 추가적인 비트코인 트랜잭션을 만들지 않아도, 온체인 수수료를 내지 않고도, 라이트닝 네트워크에서 그들이 원하는 만큼 얼마든지 지불할 수 있습니다. 
그들은 단지 처음에 비트코인(화폐)을 라이트닝 네트워크로 로드할 때, 혹은 이후 비트코인(화폐)을 라이트닝 네트워크에서 제거하기 위해 _지불_ 할 때 비트코인(블록체인)을 사용합니다.
단지 초기 로딩과 마지막 지불 트랜잭션만 비트코인 노드들이 검증하고 저장하면 되므로, 더 많은 비트코인 지불들이 오프체인에서 일어나는 결과를 가져옵니다.
노드의 부담을 줄이는 것 외에도, 라이트닝 네트워크에서 지불하면 더 쌉니다. 블록체인 수수료를 지불할 필요가 없기 때문이죠. 또 모든 사용자들이 참가하는 네트워크에 올리지 않고 영구적으로 저장되지도 않으므로, 사용자들이 더 개인적으로 이용할 수 있습니다.

라이트닝 네트워크는 초기에 비트코인을 위해 고안되었지만, 이제는 몇 가지 기본적인 기술적 요구사항만 갖추면 어느 블록체인에서든 구현될 수 있습니다. 라이트코인(Litecoin)과 같은 다른 블록체인에서는 이미 라이트닝 네트워크를 지원합니다. 게다가 몇몇 다른 블록체인들은 확장성을 위해 비슷한 "레이어 2" 해결책을 개발하고 있습니다.(((range="endofrange", startref="ix_01_introduction-asciidoc5")))(((range="endofrange", startref="ix_01_introduction-asciidoc4"))).(((range="endofrange", startref="ix_01_introduction-asciidoc3")))

=== 라이트닝 네트워크의 특징

((("Lightning Network (generally)","defining features")))라이트닝 네트워크는 비트코인이나 다른 블록체인 위에서 레이어 2 프로토콜로 동작하는 네트워크입니다. 라이트닝 네트워크는 빠르고, 안전하고, 개인적으로 쓸 수 있고, 신뢰하지 않아도 되고, 허가 없이(누구나 참여할 수 있는) 지불할 수 있게 합니다. 다음은 라이트닝 네트워크의 특징들입니다.

 * 라이트닝 네트워크의 사용자들은 실시간으로 저렴하게 서로 지불 경로를 구성할 수 있습니다.
 * 라이트닝 네트워크에서 가치를 교환하는 사용자들은 지불을 위해 블록이 네트워크에 올라갈 때까지 기다릴 필요가 없습니다.
 * 라이트닝 네트워크에서 지불이 완료되면, 보통 몇 초내로 최종 결제가 왼료되고 되돌릴 수 없습니다. 비트코인 거래처럼, 라이트닝 네트워크의 지불도 받은 사람만이 환불해줄 수 있습니다.
 * 온체인 비트코인 트랜잭션은 모두에게 알려지고 네트워크의 모든 노드들에게 검증되는 반면, 라이트닝 네트워크에서 지불은 두 노드들끼리 전달되며 모든 사람에게 보이지는 않습니다. 프라이버시가 더 강화되겠죠.
 * 비트코인 네트워크의 트랜잭션들과는 달리, 라이트닝 네트워크의 지불은 영구적으로 저장될 필요가 없습니다. 자원이 덜 필요하고, 그래서 더 싸죠. 이 특성 또한 프라이버시에 관해서 이점을 줍니다. 
 * 라이트닝 네트워크는 어니언 라우팅(onion routing, 프라이버시를 강화한 네트워크 기술)을 사용합니다. The Onion Router(Tor) 익명 네트워크에서 사용하는 프로토콜과 비슷하죠. 그래서 결제 라우팅에 참여하는 노드들도 결제 경로에서 직전과 직후 노드만 알 수 있습니다.
 * 비트코인 위에서 사용할 때 라이트닝 네트워크는 항상 사용자가 소유한 실제 비트코인을 사용합니다. 라이트닝 네트워크는 분리된 토큰이나 코인이 아니라, 비트코인 _그 자체_ 를 사용합니다.

[[라이트닝 네트워크 사용자들의 이야기]]
=== 라이트닝 네트워크 사용 사례, 사용자들, 그들의 이야기

((("Lightning Network (generally)","use cases and users")))어떻게 라이트닝 네트워크가 실제로 동작하는지, 그리고 왜 사람들이 사용하는지를 더 잘 이해하기 위해, 우리는 수많은 사용자들과 그들의 이야기를 살펴볼 것입니다.

우리가 예시로 들 사례에서, 몇몇 사람들은 이미 비트코인을 사용한 적이 있고, 아예 처음 접한 사람도 있습니다. 아래 서술된 각 사람들과 이야기는 하나 이상의 구체적인 사례를 보여줍니다. 우리는 책 전반에서 다시 그들을 볼 것입니다.

소비자::
앨리스(Alice)는 소규모 결제에서 빠르고, 안전하고, 싸고, 사생활을 보호하기를 원하는 비트코인 사용자입니다. 그녀는 라이트닝 네트워크에서 비트코인으로 커피를 삽니다.

판매자::
밥(Bob)은 "Bob's Cafe"라는 커피숍을 운영합니다. 온체인 비트코인 결제는 커피 한 잔처럼 작은 규모까지 확장할 수 없습니다. 그래서 그는 낮은 수수료로 비트코인 결제를 빠르게 받기 위해 라이트닝 네트워크를 사용합니다.

소프트웨어 서비스 사업::
찬(Chan)은 비트코인, 라이트닝 네트워크, 다른 암호화폐 관련 정보 서비스를 파냄하는 중국 기업가입니다. 그는 라이트닝 네트워크의 소액 결제를 이용하여 인터넷에서 이런 정보 서비스들을 판매하고 있습니다. 게다가 라이트닝 네트워크에서 인바운드 채널을 대여해주는 유동성 공급 서비스도 운영하고 있습니다. 임대 기간마다 소액의 비트코인 수수료를 받습니다.

게이머::
디나(Dina)는 러시아의 10대 게이머입니다. 그녀는 여러 종류의 컴퓨터 게임을 즐기지만, 그중 최애 게임은 실제 돈으로 "인게임 경제" 시스템을 구축한 게임입니다. 그녀는 게임을 즐기면서 인게임 아이템을 얻고, 이를 판매하면 돈도 벌 수 있습니다. 라이트닝 네트워크는 그녀가 인게임 아이템 같은 소규모 거래도 가능하게 해주고, 퀘스트를 수행하면서 작은 돈도 벌 수 있게 해줍니다.

=== 결론

이번 챕터에서 비트코인과 라이트닝 네트워크의 기초가 되는 근본적인 개념에 대해 이야기했습니다. 바로 공평성 프로토콜이죠.

우리는 라이트닝 네트워크의 역사와, 비트코인과 다른 블록체인 기반 네트워크을 위한 레이어 2 확장의 이유를 살펴 보았습니다.

우리는 노드, 지불 채널, 온체인 거래, 오프체인 지불 등 기초적인 용어들도 배웠죠.

마지막으로 책에서 곧 만나게 될 앨리스, 밥, 찬, 디나까지 만나보았습니다.(((range="endofrange", startref="ix_01_introduction-asciidoc0"))) 다음 챕터에서 우리는 앨리스를 만나, 그녀가 라이트닝 네트워크 지갑을 선택해서 "Bob's Cafe"에서 커피 한 잔을 사기 위해 첫 라이트닝 결제를 준비하는 그녀의 생각 프로세스를 살펴볼 것입니다.((("Bitcoin (system)","Lightning Network compared to", see="Bitcoin–Lightning Network comparisons")))((("channel", see="payment channel")))((("containers", see="Docker containers")))((("delivering payment", see="payment delivery")))((("DoS attacks", see="denial-of-service attacks")))((("encrypted message transport", see="Lightning encrypted transport protocol")))((("future issues", see="innovations in Lightning")))((("HTLCs", see="hash time-locked contracts")))((("invoices", see="Lightning invoices")))((("Lightning Network (generally)","Bitcoin compared to", see="Bitcoin–Lightning Network comparisons")))((("Lightning Network (generally)","invoices", see="Lightning invoices")))((("Lightning Network (generally)","network architecture", see="architecture, Lightning Network")))((("Lightning Network node", see="Lightning node entries")))((("Lightning payment requests", see="Lightning invoices")))((("LN node", see="Lightning node entries")))((("LND node project", see="Lightning Network Daemon node project")))((("message transport", see="Lightning encrypted transport protocol")))((("node", see="Lightning node entries")))((("payment channel","routing on network of", see="routing")))((("payment requests", see="Lightning invoices")))((("payment routing", see="routing")))((("privacy", see="breaches of privacy")))((("privacy", see="security and privacy")))((("private channels", see="unannounced channels")))((("TLV", see="Type-Length-Value")))((("wallet", see="Lightning wallet")))
